apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Must match the claim name from the pointer
  # In our case its in our mongo-stack.yaml under
  # deployment.spec.template.spec.volumes.persistentVolumeClaim.claimName
  name: mongo-pvc
spec:
  # Look for a persistent volume with this name
  storageClassName: mylocalstorage
  # Allocate disk space
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Request 20 gigs

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  # This is the persistent volume for any claims looking
  # for it
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  # Any storage type, can be EBS, in our case hostPath
  hostPath:
    path: "/mnt/some/path"
    type: DirectoryOrCreate
