apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    # Here we'll give a key value pair for the service to find this pod
    app: webapp
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
