apiVersion: apps/v1
# Literally changing replicaset to deployment
# will make this a deployment, its the same
# configuration
#kind: ReplicaSet
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  minReadySeconds: 30
  # Must add this - selector.matchLabels
  # will point to which pods should be part
  # of the replicaset.
  # This points down to spec.template.metadata.labels
  selector:
    matchLabels:
      app: webapp
  template: # Template for pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue-pod
  labels:
    # app: fleetman-queue for the service to target
    app: fleetman-queue
spec:
  containers:
    - name: fleetman-queue-pod
      image: richardchesterwood/k8s-fleetman-queue:release1
