apiVersion: v1
kind: Pod
metadata:
  name: fleetman-queue-pod
  labels:
    # app: fleetman-queue for the service to target
    app: fleetman-queue
spec:
  containers:
    - name: fleetman-queue-pod
      image: richardchesterwood/k8s-fleetman-queue:release1
